#!/bin/bash

#XU3_1

########
#LITTLE#
########

#c1
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c1/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c1_noevents_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c1_noevents_run_1_physical.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c1/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c1_noevents_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c1_noevents_run_2_physical.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c1/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c1_noevents_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c1_noevents_run_1_temperature.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c1/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c1_noevents_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c1_noevents_run_2_temperature.data

#c2
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_elall_run_1_physical.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_elall_run_2_physical.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_elall_run_1_temperature.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_elall_run_2_temperature.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39 -o 4 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_elall_run_1_events.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39 -o 4 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_elall_run_2_events.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_noevents_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_noevents_run_1_physical.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_noevents_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_noevents_run_2_physical.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_noevents_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_noevents_run_1_temperature.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_noevents_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c2_noevents_run_2_temperature.data

#c3
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_elall_run_1_physical.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_elall_run_2_physical.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_elall_run_1_temperature.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_elall_run_2_temperature.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39 -o 4 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_elall_run_1_events.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39 -o 4 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_elall_run_2_events.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_noevents_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_noevents_run_1_physical.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_noevents_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_noevents_run_2_physical.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_noevents_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_noevents_run_1_temperature.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_noevents_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c3_noevents_run_2_temperature.data

#c4
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_elall_run_1_physical.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_elall_run_2_physical.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_elall_run_1_temperature.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_elall_run_2_temperature.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39 -o 4 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_elall_run_1_events.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39 -o 4 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_elall_run_2_events.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_noevents_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_noevents_run_1_physical.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_noevents_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_noevents_run_2_physical.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_noevents_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_noevents_run_1_temperature.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/LITTLE/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_noevents_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_LITTLE_c4_noevents_run_2_temperature.data

########
#big#
########

#c1
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c1/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_elall_run_1_physical.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c1/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_elall_run_2_physical.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c1/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_elall_run_1_temperature.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c1/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_elall_run_2_temperature.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c1/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63 -o 4 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_elall_run_1_events.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c1/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63 -o 4 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_elall_run_2_events.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c1/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_noevents_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_noevents_run_1_physical.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c1/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_noevents_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_noevents_run_2_physical.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c1/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_noevents_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_noevents_run_1_temperature.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c1/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_noevents_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c1_noevents_run_2_temperature.data

#c2
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_elall_run_1_physical.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_elall_run_2_physical.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_elall_run_1_temperature.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_elall_run_2_temperature.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63 -o 4 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_elall_run_1_events.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63 -o 4 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_elall_run_2_events.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_noevents_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_noevents_run_1_physical.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_noevents_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_noevents_run_2_physical.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_noevents_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_noevents_run_1_temperature.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c2/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_noevents_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c2_noevents_run_2_temperature.data

#c3
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_elall_run_1_physical.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_elall_run_2_physical.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_elall_run_1_temperature.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_elall_run_2_temperature.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63 -o 4 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_elall_run_1_events.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63 -o 4 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_elall_run_2_events.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_noevents_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_noevents_run_1_physical.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_noevents_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_noevents_run_2_physical.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_noevents_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_noevents_run_1_temperature.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c3/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_noevents_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c3_noevents_run_2_temperature.data

#c4
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_elall_run_1_physical.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_elall_run_2_physical.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_elall_run_1_temperature.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_elall_run_2_temperature.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_elall_run_1.data -b PARSEC_fullset.data -p 8 -e 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63 -o 4 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_elall_run_1_events.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_elall_run_2.data -b PARSEC_fullset.data -p 8 -e 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63 -o 4 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_elall_run_2_events.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_noevents_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_noevents_run_1_physical.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_noevents_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 1 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_noevents_run_2_physical.data

./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_noevents_run_1.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_noevents_run_1_temperature.data
./octave_makemodel.sh -r Concatenated_Results/cset_data/xu3_1/PARSEC/Multithread/allevents/big/c4/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_noevents_run_2.data -b PARSEC_fullset.data -p 8 -e 5 -o 5 -s Analysed_Results/cset_data/xu3_1/multithread/xu3_1_eMMC_perfcpu_cset_PARSEC_greenbench_big_c4_noevents_run_2_temperature.data
